language: generic
sudo: required

before_install:
    - sudo apt-add-repository -y universe
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt update -y
    - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gfortran-8 libosmesa-dev
    - wget https://sourceforge.net/projects/asymptote/files/2.45/asymptote-2.45.src.tgz
    - tar -xzf asymptote-2.45.src.tgz
    - cd asymptote-2.45/
    - ./configure --enable-offscreen
    - make all
    - sudo make install
    - cd ..
    - rm -rf asymptote-2.45

script:
    - latexmk -help
    - make
    - make clean

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
