language: generic
sudo: required

addons:
    apt:
        packages:
            - texlive-full
            - latexmk
            - asymptote
script:
    - make
    - make clean

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
