language: generic
sudo: required

before_install:
    - sudo apt update -y
    - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install texlive-full asymptote latexmk

script:
    - make

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
