language: generic
sudo: required

before_install:
    - sudo apt-add-repository -y universe
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo add-apt-repository -y ppa:jonathonf/texlive
    - sudo apt update -y
    - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
    - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install texlive-full latexmk asymptote
      # - export CC=gcc-8 CXX=g++-8
      # - wget https://sourceforge.net/projects/asymptote/files/2.45/asymptote-2.45.src.tgz
      # - tar -xzf asymptote-2.45.src.tgz
      # - cd asymptote-2.45/
      # - ./configure --enable-offscreen
      # - make all
      # - sudo make install
      # - cd ..
      # - rm -rf asymptote-2.45

script:
    - latexmk -help
    - make
    - make clean

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
