language: generic
sudo: required

services:
    - docker

before_install:
    - docker pull pritunl/archlinux:latest
    - docker run -d --name arch -v $(pwd):/travis pritunl/archlinux:latest tail -f /dev/null
    - docker exec -t arch bash -c "pacman -S --noconfirm texlive-most asymptote make biber"
    - docker exec -t arch bash -c "ln -s /usr/bin/vendor_perl/biber /usr/bin/biber"

script:
    - docker exec -t arch bash -c "cd /travis; make && make clean"
    - rm .gitignore

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
