language: generic
sudo: required

addons:
    apt:
        update: true
        packages:
            - libosmesa-dev
            - texlive-full
            - latexmk
            - asymptote
script:
    - latexmk -help
    - make
    - make clean

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
