name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile project description
        run: make project.pdf
        #uses: xu-cheng/latex-action@v2
        #with:
        #  root_file: project.tex
